declare const process: {
  env: {
    EXPO_PUBLIC_TICKETMASTER_KEY?: string;
    EXPO_PUBLIC_GOOGLE_PLACES_KEY?: string;
    EXPO_PUBLIC_SEATGEEK_KEY?: string;
    EXPO_PUBLIC_GEMINI_MODEL?: string;
    EXPO_PUBLIC_FUNCTIONS_REGION?: string;
    EXPO_PUBLIC_ALLOW_DIRECT_MODEL_CALLS?: string;
    EXPO_PUBLIC_FIREBASE_APPCHECK_SITE_KEY?: string;
    EXPO_PUBLIC_SUPPORT_EMAILS?: string;
    EXPO_PUBLIC_BUSINESS_ADMIN_EMAILS?: string;
    EXPO_PUBLIC_ADMIN_EMAILS?: string;
    EXPO_PUBLIC_BUSINESS_PREMIUM_EMAILS?: string;
  };
};
